import { test,expect } from "@playwright/test";
import { rememberAdminSession,restoreAdminSession } from "./support/admin-session";

test("real join code receipt recovery and first membership preserve source without reward writes",async({page,context},info)=>{
 test.skip(!process.env.TEST_HARBOR_ADMIN_USERNAME||!process.env.TEST_HARBOR_ADMIN_PASSWORD,"Provide isolated Harbor administrator credentials");test.setTimeout(45_000);page.setDefaultTimeout(8000);
 const brand="0199a000-0000-7000-8000-000000000002",base="http://localhost:5174/api/v1/admin",origin="http://localhost:5174",uid=()=>crypto.randomUUID(),headers={Origin:origin,"X-Brand-ID":brand};
 const call=async(path:string,method:"GET"|"POST"|"PUT",body?:unknown,status=200)=>{const r=await page.request.fetch(`${base}${path}`,{method,headers:{...headers,...(method==="GET"?{}:{"Idempotency-Key":uid()})},...(body===undefined?{}:{data:body})});expect(r.status(),await r.text()).toBe(status);return(await r.json()).data};
 if(!await restoreAdminSession(context,process.env.TEST_HARBOR_ADMIN_USERNAME!,brand)){const r=await page.request.post(`${base}/auth/login`,{headers:{...headers,"Idempotency-Key":uid()},data:{identifier:process.env.TEST_HARBOR_ADMIN_USERNAME,password:process.env.TEST_HARBOR_ADMIN_PASSWORD}});expect(r.status(),await r.text()).toBe(200)}
 rememberAdminSession(process.env.TEST_HARBOR_ADMIN_USERNAME!,await context.cookies(`${base}/me`));
 let policy=await call("/agent-policy","GET");if(!policy.config.enabled)policy=await call("/agent-policy","PUT",{version:policy.version,config:{enabled:true,max_depth:3,ratio_cap:"0.1",mode:"loss",cycle:"monthly"},reason:"isolated join-code fixture policy"});
 let root=(await call("/agents/tree?limit=20&offset=0","GET")).items[0];if(!root){const owner=await call("/users","POST",{username:`code_owner_${uid().replaceAll("-","").slice(0,10)}`,password:"code-owner-test-password",reason:"isolated source owner"},201);root=await call("/agents","POST",{policy_version:policy.version,member_id:owner.member_id,parent_id:null,parent_version:null,config:{ratio:"0.08",mode:null,status:"active",can_create_children:true},reason:"isolated root invitation source"},201)}
 const before=await call(`/wallets/${root.member_id}`,"GET"),ledgerBefore=await call(`/wallets/${root.member_id}/ledger`,"GET");
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.goto("http://localhost:5174");await page.getByLabel("选择真实后台品牌",{exact:true}).selectOption(brand);
 if(info.project.name==="mobile"){await page.locator(".mobile-nav button").nth(4).click();await page.locator(".mobile-more-menu").getByRole("button",{name:/加入码/}).click()}else await page.locator(".side-nav").getByRole("button",{name:/加入码/}).click();
 const panel=page.locator(".join-codes");await expect(panel.getByRole("heading",{name:"加入码管理",exact:true})).toBeVisible();await panel.getByRole("button",{name:"新建加入码",exact:true}).click();const form=panel.locator(".jc-form");await form.getByRole("combobox",{name:"加入码类型",exact:true}).selectOption("agent");await form.getByLabel("归属会员 UUID",{exact:true}).fill(root.member_id);await form.getByLabel("代理 UUID",{exact:true}).fill(root.id);
 const starts=new Date(Date.now()-3600_000).toISOString(),expires=new Date(Date.now()+3600_000).toISOString();await form.getByLabel("开始时间（RFC3339；留空表示不限）",{exact:true}).fill(starts);await form.getByLabel("到期时间（RFC3339；留空表示不限）",{exact:true}).fill(expires);await form.getByLabel("管理原因",{exact:true}).fill("new real agent invitation without rewards");
 const writes:Array<{body:string|null,key:string|undefined}>=[];await page.route("**/api/v1/admin/join-codes",async route=>{if(route.request().method()!=="POST"){await route.continue();return}writes.push({body:route.request().postData(),key:route.request().headers()["idempotency-key"]});const response=await route.fetch();expect(response.status(),await response.text()).toBe(201);if(writes.length===1)await route.abort("failed");else await route.fulfill({response})});
 await form.getByRole("button",{name:"核对并创建",exact:true}).click();const review=panel.locator(".jc-review");await review.getByRole("checkbox").check();await review.getByRole("button",{name:"确认提交",exact:true}).click();await expect(panel.getByRole("status").filter({hasText:"未知"})).toBeVisible();await panel.getByRole("button",{name:"查询",exact:true}).click();await expect(review).toBeVisible();await review.getByRole("checkbox").check();await review.getByRole("button",{name:"按原键重试",exact:true}).click();await expect(review).toHaveCount(0);expect(writes).toHaveLength(2);expect(writes[0]).toEqual(writes[1]);await page.unroute("**/api/v1/admin/join-codes");
 const codes=await call(`/join-codes?kind=agent&owner_member_id=${root.member_id}&limit=100&offset=0`,"GET");const code=codes.items.find((x:{starts_at:string|null})=>x.starts_at!==null&&Date.parse(x.starts_at)===Date.parse(starts));expect(code).toBeTruthy();expect(code).toMatchObject({kind:"agent",owner_member_id:root.member_id,agent_id:root.id,usable:true,version:1});
 const guest=await context.newPage();guest.on("pageerror",e=>errors.push(e.message));await guest.addInitScript(()=>localStorage.setItem("luma-language","en"));await guest.route("http://harbor.localhost:5173/api/**",async route=>{const response=await route.fetch({url:route.request().url().replace("harbor.localhost","localhost"),headers:{...(await route.request().allHeaders()),host:"harbor.localhost:5173"}});await route.fulfill({response})});
 try{await guest.goto("http://harbor.localhost:5173/register");const username=`code_join_${uid().replaceAll("-","").slice(0,11)}`;await guest.getByLabel("Choose a username or phone",{exact:true}).fill(username);await guest.getByLabel("Password",{exact:true}).fill("join-code-test-password-2026");await guest.getByRole("combobox",{name:"Optional join source",exact:true}).selectOption("agent");await guest.getByLabel("24-character code",{exact:true}).fill(code.code.toLowerCase());await guest.locator('.auth-form input[type="checkbox"]').nth(0).check();await guest.locator('.auth-form input[type="checkbox"]').nth(1).check();
  const registered=guest.waitForResponse(r=>r.url().endsWith("/auth/register")&&r.request().method()==="POST");await guest.getByRole("button",{name:/Continue/}).click();const response=await registered;expect(response.status(),await response.text()).toBe(201);const user=(await response.json()).data;expect(response.request().postDataJSON().agent_code).toBe(code.code);await expect(guest).toHaveURL(/\/account$/);
  const referral=await call("/join-codes","POST",{kind:"referral",owner_member_id:user.member.id,agent_id:null,starts_at:null,expires_at:null,reason:"assign real member-owned referral without rewards"},201);
  await guest.goto("http://harbor.localhost:5173/invites");const own=guest.locator(".join-codes-page");await expect(own).toContainText(code.code);await expect(own).toContainText(referral.code);expect(await guest.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await own.screenshot({path:info.outputPath("s6-f-user-codes.png")});
  await panel.locator(".jc-row").filter({hasText:code.code}).getByRole("button",{name:"详情与历史",exact:true}).click();await form.getByRole("combobox",{name:"状态",exact:true}).selectOption("disabled");await form.getByLabel("管理原因",{exact:true}).fill("stop new joins without changing existing attribution");await form.getByRole("button",{name:"核对并保存",exact:true}).click();await review.getByRole("checkbox").check();const updated=page.waitForResponse(r=>r.url().endsWith(`/join-codes/${code.id}`)&&r.request().method()==="PUT");await review.getByRole("button",{name:"确认提交",exact:true}).click();expect((await updated).status()).toBe(200);await expect(review).toHaveCount(0);await panel.getByRole("button",{name:"查询历史",exact:true}).click();await expect(panel.locator(".jc-history-row")).toHaveCount(2);
  await guest.reload();await expect(own).toContainText(code.code);await expect(own).toContainText(referral.code);const attr=await guest.evaluate(async()=>{const r=await fetch("/api/v1/me/attribution",{credentials:"include"});return{status:r.status,body:await r.json()}});expect(attr.status).toBe(200);expect(attr.body.data).toMatchObject({brand_id:brand,member_id:user.member.id,join_method:"agent_code",code_id:code.id,source_code:code.code,legacy:false});const wallet=await call(`/wallets/${user.member.id}`,"GET");expect(wallet.display_points).toBe("0");const userLedger=await call(`/wallets/${user.member.id}/ledger`,"GET");expect(userLedger.items).toHaveLength(0);
  expect(await call(`/wallets/${root.member_id}`,"GET")).toEqual(before);expect(await call(`/wallets/${root.member_id}/ledger`,"GET")).toEqual(ledgerBefore);expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await panel.screenshot({path:info.outputPath("s6-f-admin-codes.png")});
 }finally{await guest.unrouteAll({behavior:"wait"});await guest.close()}
});
