import {expect,type Page,type BrowserContext,type TestInfo} from '@playwright/test'
import {createHash} from 'node:crypto'
const brand='0199a000-0000-7000-8000-000000000001'
export async function responseData(response: Awaited<ReturnType<Page['request']['get']>>, status=200) {
  expect(response.status()).toBe(status)
  const envelope=await response.json()
  expect(envelope.success).toBe(true)
  return envelope.data
}
export async function checkWithdrawalObservability(page:Page, context:BrowserContext, info:TestInfo, order:{member_id:string}, origins:{userOrigin:string,adminOrigin:string}, errors:string[],expectedReviewing:string) {
  const {userOrigin,adminOrigin}=origins
  const userPanel=page.locator('.withdrawal-page')
  const adminHeaders={'X-Brand-ID':brand}
  const workbench=await responseData(await page.request.get(`${adminOrigin}/api/v1/admin/workbench`,{headers:adminHeaders}))
  expect(workbench.withdrawals.status).toBe('ready')
  expect(workbench.withdrawals.data).toEqual({reviewing_count:expectedReviewing,reviewing_points:String(BigInt(expectedReviewing)*80n),processing_count:'0',processing_points:'0'})
  if(info.project.name==='mobile') await page.locator('.mobile-nav button').nth(0).click()
  else await page.locator('.side-nav').getByRole('button',{name:/Dashboard/}).click()
  const withdrawalCard=page.locator('.workbench .card').filter({has:page.getByRole('heading',{name:'Withdrawals',exact:true})})
  await expect(withdrawalCard).toContainText('Ready')
  await expect(withdrawalCard).toContainText('does not indicate eligibility, actual payment, or profit')
  await withdrawalCard.screenshot({path:info.outputPath('withdrawal-workbench.png')})
  if(info.project.name==='mobile') {await page.locator('.mobile-nav button').nth(4).click();await page.locator('.mobile-more-menu').getByRole('button',{name:/Reports.*reconciliation/}).click()}
  else await page.locator('.side-nav').getByRole('button',{name:/Reports.*reconciliation/}).click()
  const reportPanel=page.locator('.withdrawal-report')
  await expect(reportPanel.getByRole('heading',{name:'Withdrawal report',exact:true})).toBeVisible()
  await reportPanel.getByLabel('Member UUID',{exact:true}).fill(order.member_id)
  await reportPanel.getByLabel('Group by',{exact:true}).selectOption('state')
  const until=new Date(Date.now()+300_000),pad=(n:number)=>String(n).padStart(2,'0')
  await reportPanel.getByLabel('To',{exact:true}).fill(`${until.getFullYear()}-${pad(until.getMonth()+1)}-${pad(until.getDate())}T${pad(until.getHours())}:${pad(until.getMinutes())}:${pad(until.getSeconds())}`.replace(/:00$/,''))
  const reportResponse=page.waitForResponse(r=>r.url().includes('/api/v1/admin/reports/withdrawal?'))
  await reportPanel.getByRole('button',{name:'Query',exact:true}).click()
  const report=await responseData(await reportResponse)
  expect(report.summary.order_count).toBe('1')
  expect(report.summary.requested_points).toBe('80')
  expect(report.summary[info.project.name==='mobile'?'paid_points':'failed_points']).toBe('80')
  await expect(reportPanel.locator('.metrics')).toBeVisible()
  await expect(reportPanel.locator('tbody')).toContainText(info.project.name==='mobile'?'Paid':'Failed')
  const downloadEvent=page.waitForEvent('download')
  await reportPanel.getByRole('button',{name:'Export full CSV',exact:true}).click()
  const download=await downloadEvent
  expect(download.suggestedFilename()).toMatch(/^lottery-withdrawal-.*\.csv$/)
  const params=new URLSearchParams({from:report.query.from,to:report.query.to,group_by:'state',member_id:order.member_id})
  const exported=await page.request.get(`${adminOrigin}/api/v1/admin/reports/withdrawal/export?${params}`,{headers:adminHeaders})
  expect(exported.status()).toBe(200)
  const bytes=await exported.body()
  expect(bytes.subarray(0,3).toString('hex')).toBe('efbbbf')
  expect(createHash('sha256').update(bytes).digest('hex')).toBe(exported.headers()['x-report-sha256'])
  expect(bytes.toString()).toContain(info.project.name==='mobile'?'paid':'failed')
  await page.getByTestId('admin-language').selectOption('zh-CN')
  await expect(reportPanel.getByRole('heading',{name:'提现报表',exact:true})).toBeVisible()
  await expect(reportPanel.locator('.metrics')).toBeVisible()
  await page.getByTestId('admin-language').selectOption('en')
  await reportPanel.screenshot({path:info.outputPath('withdrawal-report.png')})
  await page.goto(`${userOrigin}/withdraw`)
  await expect(userPanel).toContainText(info.project.name==='mobile' ? 'Paid' : 'Failed')
  const wallet=await responseData(await page.request.get(`${userOrigin}/api/v1/wallet`))
  expect(wallet.withdrawal_points).toBe('0')
  expect(wallet.by_source.recharge.available).toBe(info.project.name==='mobile' ? '60' : '100')
  expect(wallet.by_source.winning.available).toBe(info.project.name==='mobile' ? '35' : '60')
  expect(wallet.by_source.gift.available).toBe(info.project.name==='mobile' ? '25' : '40')
  const dimensions=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,visible:visualViewport?.width}))
  expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.width+1)
  expect(dimensions.visible).toBe(page.viewportSize()!.width)
  await userPanel.screenshot({path:info.outputPath('withdrawal-user.png')})
  await expect.poll(async()=>{
    const inbox=await responseData(await page.request.get(`${userOrigin}/api/v1/notifications?limit=20&offset=0`))
    return inbox.items.filter((n:{event_type:string})=>n.event_type.startsWith('withdrawal.order.')).length
  }).toBe(3)
  await page.goto(`${userOrigin}/notifications`)
  const inboxPanel=page.locator('.notifications-panel')
  await expect(inboxPanel.locator('.notification-protected-note')).toHaveCount(3)
  await expect(inboxPanel).toContainText('not proof of an external transfer')
  await expect(inboxPanel).not.toContainText('中文审核原因保持原值')
  await expect(inboxPanel).not.toContainText('内部模拟结果，无外部转账')
  await inboxPanel.screenshot({path:info.outputPath('withdrawal-notifications.png')})
  expect(await responseData(await page.request.get(`${userOrigin}/api/v1/wallet`))).toEqual(wallet)
  expect(errors).toEqual([])
  expect(await context.cookies()).toEqual(expect.arrayContaining([expect.objectContaining({httpOnly:true,sameSite:'Strict'})]))
}
