import { afterEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { createRenderer, h, nextTick, ref, type Component } from "vue";
import * as VueRuntime from "vue";
import * as AdminApi from "./admin-api";
import * as AdminI18n from "./i18n";
import { adminI18nKey, createAdminI18n } from "./i18n";
import type { AdminAccount } from "./admin-api";
import * as AdjustmentApi from "./commission-adjustments-api";
import * as AdjustmentState from "./commission-adjustments-state";
import { compileScript, parse } from "vue/compiler-sfc";
import ts from "typescript";

const brand="11111111-1111-4111-8111-111111111111",actor="33333333-3333-4333-8333-333333333333",payment="44444444-4444-4444-8444-444444444444",targetId="55555555-5555-4555-8555-555555555555",earning="66666666-6666-4666-8666-666666666666",ledger="77777777-7777-4777-8777-777777777777",audit="88888888-8888-4888-8888-888888888888",record="99999999-9999-4999-8999-999999999999",brandB="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",paymentB="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",targetB="cccccccc-cccc-4ccc-8ccc-cccccccccccc",now="2026-10-07T00:00:00Z";
const account:AdminAccount={id:actor,super_admin:false,brand_ids:[brand],permissions:[],permissions_by_brand:{[brand]:["commission.view.brand","commission_adjustment.write.brand"]}};
type Node={tag:string;props:Record<string,unknown>;children:Node[];text:string;parent?:Node;value?:string;checked?:boolean;addEventListener:(...args:unknown[])=>void;removeEventListener:(...args:unknown[])=>void;getRootNode:()=>Node;options:Node[]};
function element(tag:string):Node{return{tag,props:{},children:[],text:"",value:"",checked:false,addEventListener(){},removeEventListener(){},getRootNode(){return this;},get options(){return this.children.filter(x=>x.tag==="option");}};}
const renderer=createRenderer<Node,Node>({createElement:element,createText:text=>({...element("#text"),text}),createComment:text=>({...element("#comment"),text}),setText:(n,text)=>{n.text=text;},setElementText:(n,text)=>{n.text=text;n.children=[];},patchProp:(n,k,_old,v)=>{n.props[k]=v;if(k==="value")n.value=String(v??"");},insert:(n,p,a)=>{if(n.parent){const i=n.parent.children.indexOf(n);if(i>=0)n.parent.children.splice(i,1);}n.parent=p;const i=a?p.children.indexOf(a):-1;if(i<0)p.children.push(n);else p.children.splice(i,0,n);},remove:n=>{if(!n.parent)return;const i=n.parent.children.indexOf(n);if(i>=0)n.parent.children.splice(i,1);n.parent=undefined;},parentNode:n=>n.parent??null,nextSibling:n=>n.parent?n.parent.children[n.parent.children.indexOf(n)+1]??null:null});
function compile():Component{const source=readFileSync(new URL("./CommissionAdjustmentsManagement.vue",import.meta.url),"utf8"),descriptor=parse(source,{filename:"CommissionAdjustmentsManagement.vue"}).descriptor;const javascript=ts.transpileModule(compileScript(descriptor,{id:"commission-adjustments-test",inlineTemplate:true}).content,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;const modules:Record<string,unknown>={vue:VueRuntime,"./admin-api":AdminApi,"./i18n":AdminI18n,"./commission-adjustments-api":AdjustmentApi,"./commission-adjustments-state":AdjustmentState};const body=javascript.replace(/^import\s+\{([\s\S]*?)\}\s+from\s+["']([^"']+)["'];?\s*$/gm,(_m,b:string,s:string)=>`const {${b.replace(/\s+as\s+/g,": ")}}=__modules[${JSON.stringify(s)}];`).replace(/export\s+default\s+/,"return ");return new Function("__modules",body)(modules) as Component;}
const ComponentUnderTest=compile();
function paidTarget(overrides:Record<string,unknown>={}){return{id:targetId,brand_id:brand,payment_id:payment,earning_id:earning,agent_id:actor,member_id:actor,original_points:"9007199254740993",state:"paid",ledger_entry_id:ledger,paid_at:now,adjustment_version:1,adjusted_points:"9007199254740993",last_adjustment_id:null,...overrides};}
function historyItem(version=2,target=targetId){return{id:record,brand_id:brand,target_id:target,payment_id:payment,version,points_before:"9007199254740993",points_after:"9007199254740988",delta_points:"-5",ledger_entry_id:ledger,audit_log_id:audit,created_by:actor,reason:"Previous correction",point_policy_version:"3",created_at:now};}
function ok(data:unknown,status=200){return new Response(JSON.stringify({success:true,data}),{status});}function fail(status:number){return new Response(JSON.stringify({success:false,error:{code:"CONFLICT",message:"version conflict"}}),{status});}
function setupFetch(options:{post?:(init:RequestInit|undefined)=>Promise<Response>|Response;slowTargets?:Promise<Response>;slowThirdHistory?:Promise<Response>;targetFor?:(url:string)=>Response;historyFor?:(url:string)=>Response}={}){vi.stubGlobal("Document",class{});vi.stubGlobal("ShadowRoot",class{});const calls:Array<{url:string;init?:RequestInit}>=[];let targetReads=0,historyReads=0;const fetcher=vi.fn<typeof fetch>(async(input,init)=>{const url=String(input);calls.push({url,init});if(url.includes("/targets?")){targetReads++;if(targetReads===1&&options.slowTargets)return options.slowTargets;const custom=options.targetFor?.(url);if(custom)return custom;const query=new URL(url,"http://local").searchParams;return ok({brand_id:brand,payment_id:payment,items:[paidTarget()],total_count:"1",limit:Number(query.get("limit")),offset:Number(query.get("offset"))});}if(url.includes("/adjustments?")){historyReads++;if(historyReads===3&&options.slowThirdHistory)return options.slowThirdHistory;const custom=options.historyFor?.(url);if(custom)return custom;const query=new URL(url,"http://local").searchParams;return ok({brand_id:brand,target_id:targetId,items:[historyItem()],total_count:"1",limit:Number(query.get("limit")),offset:Number(query.get("offset"))});}if(url.endsWith("/adjustments")&&init?.method==="POST")return options.post?.(init)??ok(historyItem(JSON.parse(String(init.body)).version+1),201);return fail(404);});vi.stubGlobal("fetch",fetcher);return{calls,fetcher};}
function text(n:Node):string{return n.text+n.children.map(text).join("");}function find(n:Node,p:(x:Node)=>boolean):Node|null{if(p(n))return n;for(const child of n.children){const x=find(child,p);if(x)return x;}return null;}function testId(n:Node,id:string){return find(n,x=>x.props["data-testid"]===id);}function button(n:Node,label:string){return find(n,x=>x.tag==="button"&&text(x).includes(label));}function click(n:Node|null){expect(n).not.toBeNull();(n!.props.onClick as (()=>void)|undefined)?.();}function submit(n:Node|null){expect(n).not.toBeNull();(n!.props.onSubmit as ((event:unknown)=>void)|undefined)?.({preventDefault(){}});}function model(n:Node|null,v:unknown){expect(n).not.toBeNull();(n!.props["onUpdate:modelValue"] as ((value:unknown)=>void)|undefined)?.(v);}async function flush(){for(let i=0;i<18;i++)await Promise.resolve();await nextTick();}
function mount(acct=account,brandId=brand,paymentId=payment){const props=ref({account:acct,brandId,paymentId,paymentState:"paid",brandStatus:"active"}),container=element("root"),app=renderer.createApp({setup:()=>()=>h(ComponentUnderTest,{...props.value})});app.provide(adminI18nKey,createAdminI18n());app.mount(container);return{app,container,props};}
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();AdjustmentState.clearAllPendingCommissionAdjustments();});
describe("CommissionAdjustmentsManagement real Vue component",()=>{
  it("cancels a completed conflict review when ordinary history pagination changes the displayed evidence", async () => {
    setupFetch({post:()=>fail(409),historyFor:url=>{
      const q=new URL(url,"http://local").searchParams,offset=Number(q.get("offset"));
      return ok({brand_id:brand,target_id:targetId,items:offset===0?Array.from({length:20},(_,i)=>historyItem(i+2)):[historyItem(22)],total_count:"21",limit:20,offset});
    }});
    const mounted=mount();await flush();
    model(testId(mounted.container,"adjustment-points"),"9007199254740988");model(testId(mounted.container,"adjustment-reason"),"Review version conflict");await flush();
    submit(find(mounted.container,n=>n.tag==="form"));await flush();model(testId(mounted.container,"adjustment-confirmed"),true);click(testId(mounted.container,"adjustment-confirm-submit"));await flush();
    click(button(mounted.container,"重读目标和历史"));await flush();
    model(find(testId(mounted.container,"adjustment-conflict")!,n=>n.tag==="input"),true);await flush();
    expect(button(mounted.container,"确认丢弃并允许重新审核")?.props.disabled).toBe(false);
    const navigation=find(mounted.container,n=>n.props["aria-label"]==="Adjustment history pages");click(button(navigation!,"下一页"));await flush();
    expect(button(mounted.container,"确认丢弃并允许重新审核")?.props.disabled).toBe(true);
    expect(AdjustmentState.getPendingCommissionAdjustmentIntent({accountId:actor,brandId:brand,paymentId:payment,targetId})).not.toBeNull();
    mounted.app.unmount();
  });
  it("renders read-only super-admin history and never exposes a write form",async()=>{setupFetch();const mounted=mount({...account,super_admin:true,platform_permissions:["commission.view.platform"],permissions_by_brand:{}});await flush();expect(text(mounted.container)).toContain("只读权限");expect(testId(mounted.container,"adjustment-review")?.props.disabled).toBe(true);expect(text(mounted.container)).toContain("不可变修正历史");mounted.app.unmount();});
  it("discards a late target response after brand, payment and account scope changes",async()=>{let resolve!:(r:Response)=>void;const slow=new Promise<Response>(r=>resolve=r);const alternateAccount:AdminAccount={...account,id:"dddddddd-dddd-4ddd-8ddd-dddddddddddd",brand_ids:[brandB],permissions_by_brand:{[brandB]:["commission.view.brand"]}};setupFetch({slowTargets:slow,targetFor:url=>url.includes(paymentB)?ok({brand_id:brandB,payment_id:paymentB,items:[paidTarget({id:targetB,brand_id:brandB,payment_id:paymentB})],total_count:"1",limit:20,offset:0}):fail(404)});const mounted=mount();await flush();mounted.props.value={...mounted.props.value,account:alternateAccount,brandId:brandB,paymentId:paymentB};await flush();expect(text(mounted.container)).toContain(targetB);expect(text(mounted.container)).not.toContain(targetId);resolve(ok({brand_id:brand,payment_id:payment,items:[paidTarget()],total_count:"1",limit:20,offset:0}));await flush();expect(text(mounted.container)).toContain(targetB);expect(text(mounted.container)).not.toContain(targetId);mounted.app.unmount();});
  it("paginates targets and immutable history independently",async()=>{const serial=(n:number)=>`eeeeeeee-eeee-4eee-8eee-${String(n).padStart(12,"0")}`;const targets20=Array.from({length:20},(_,i)=>paidTarget({id:serial(i+1)}));setupFetch({targetFor:url=>{const q=new URL(url,"http://local").searchParams,offset=Number(q.get("offset")),limit=Number(q.get("limit"));return ok({brand_id:brand,payment_id:payment,items:offset===0?targets20:[paidTarget({id:targetB})],total_count:"21",limit,offset});},historyFor:url=>{const q=new URL(url,"http://local").searchParams,offset=Number(q.get("offset")),limit=Number(q.get("limit")),requestedTarget=new URL(url,"http://local").pathname.split("/").at(-2)!;return ok({brand_id:brand,target_id:requestedTarget,items:offset===0?Array.from({length:20},(_,i)=>historyItem(i+2,requestedTarget)):[historyItem(22,requestedTarget)],total_count:"21",limit,offset});}});const mounted=mount();await flush();expect(text(mounted.container)).toContain("1–20 / 21");click(button(mounted.container,"下一页"));await flush();expect(text(mounted.container)).toContain(targetB);expect(text(mounted.container)).toContain("21–21 / 21");expect(text(mounted.container)).toContain("v2");const historyNav=find(mounted.container,n=>n.props["aria-label"]==="Adjustment history pages");click(button(historyNav!,"下一页"));await flush();expect(text(mounted.container)).toContain("21–21 / 21");expect(text(mounted.container)).toContain("v22");mounted.app.unmount();});
  it("freezes exact large integer request through unknown outcome and remount even after the head changes",async()=>{let attempts=0;const server=setupFetch({post:()=>{attempts++;if(attempts===1)throw new Error("connection lost");return ok(historyItem(2),201);},targetFor:()=>{const latest=attempts>=1;return ok({brand_id:brand,payment_id:payment,items:[paidTarget(latest?{adjustment_version:2,adjusted_points:"9007199254740988",last_adjustment_id:record}:{})],total_count:"1",limit:20,offset:0});}});let mounted=mount();await flush();model(testId(mounted.container,"adjustment-points"),"9007199254740988");model(testId(mounted.container,"adjustment-reason"),"Fix ✅");await flush();submit(find(mounted.container,n=>n.tag==="form"));await flush();expect(text(testId(mounted.container,"adjustment-review-dialog")!)).toContain("-5");model(testId(mounted.container,"adjustment-confirmed"),true);click(testId(mounted.container,"adjustment-confirm-submit"));await flush();expect(text(mounted.container)).toContain("结果未知");mounted.app.unmount();mounted=mount();await flush();expect(text(mounted.container)).toContain("待确认请求");click(button(mounted.container,"使用原请求重试"));await flush();const recoveryDialog=text(testId(mounted.container,"adjustment-review-dialog")!);expect(recoveryDialog).toContain("9007199254740993");expect(recoveryDialog).toContain("-5");const before=text(testId(mounted.container,"adjustment-review-key")!);model(testId(mounted.container,"adjustment-confirmed"),true);click(testId(mounted.container,"adjustment-confirm-submit"));await flush();const posts=server.calls.filter(c=>c.init?.method==="POST");expect(posts).toHaveLength(2);expect(posts.map(c=>c.init?.body)).toEqual([posts[0].init?.body,posts[0].init?.body]);expect(new Headers(posts[0].init?.headers).get("Idempotency-Key")).toBe(new Headers(posts[1].init?.headers).get("Idempotency-Key"));expect(new Headers(posts[1].init?.headers).get("X-Commission-Payment-Actor-ID")).toBe(actor);expect(text(mounted.container)).toContain("服务器回执");expect(text(mounted.container)).toContain("当前状态来自独立重读");expect(before).toBeTruthy();mounted.app.unmount();});
  it("finds a conflicted target on a later page and requires fresh target plus history reads",async()=>{const slowHistory=(()=>{let resolve!:(v:Response)=>void;const promise=new Promise<Response>(r=>resolve=r);return{promise,resolve};})(),serial=(n:number)=>`eeeeeeee-eeee-4eee-8eee-${String(n).padStart(12,"0")}`;const makePage=(offset:number,limit:number)=>{const items=Array.from({length:limit},(_,i)=>paidTarget({id:serial(offset+i+1)}));if(offset===20)items[0]=paidTarget();if(offset===0&&limit===100)items[30]=paidTarget();return{brand_id:brand,payment_id:payment,items,total_count:"120",limit,offset};};const server=setupFetch({post:()=>fail(409),slowThirdHistory:slowHistory.promise,targetFor:url=>{const q=new URL(url,"http://local").searchParams;return ok(makePage(Number(q.get("offset")),Number(q.get("limit"))));}});const mounted=mount();await flush();click(button(mounted.container,"下一页"));await flush();expect(text(mounted.container)).toContain(targetId);model(testId(mounted.container,"adjustment-points"),"9007199254740988");model(testId(mounted.container,"adjustment-reason"),"Needs correction");await flush();submit(find(mounted.container,n=>n.tag==="form"));await flush();model(testId(mounted.container,"adjustment-confirmed"),true);click(testId(mounted.container,"adjustment-confirm-submit"));await flush();expect(text(mounted.container)).toContain("409 原请求冻结");click(button(mounted.container,"重读目标和历史"));await flush();click(testId(mounted.container,"adjustments-refresh"));await flush();slowHistory.resolve(ok({brand_id:brand,target_id:targetId,items:[historyItem()],total_count:"1",limit:20,offset:0}));await flush();expect(button(mounted.container,"确认丢弃并允许重新审核")?.props.disabled).toBe(true);click(button(mounted.container,"重读目标和历史"));await flush();expect(text(mounted.container)).toContain(targetId);model(find(testId(mounted.container,"adjustment-conflict")!,n=>n.tag==="input"),true);click(button(mounted.container,"确认丢弃并允许重新审核"));await flush();expect(text(mounted.container)).toContain("已丢弃旧请求");expect(server.calls.filter(c=>c.init?.method==="POST")).toHaveLength(1);mounted.app.unmount();});
});
