<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from "vue";
import { AdminApiError, type AdminAccount } from "./admin-api";
import { useAdminI18n } from "./i18n";
import { createWithdrawalReportApi, withdrawalReportPermissions, type WithdrawalGroup, type WithdrawalReport, type WithdrawalReportQuery } from "./withdrawal-report-api";

const props=defineProps<{account:AdminAccount;brandId:string}>();
const emit=defineEmits<{(event:"session-invalid"):void}>();
const api=createWithdrawalReportApi();
const {t,locale}=useAdminI18n();
const permissions=computed(()=>withdrawalReportPermissions(props.account,props.brandId));
const toLocal=(d:Date)=>{const p=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`};
const roundedNow=new Date(Math.ceil(Date.now()/1000)*1000);const toDraft=ref(toLocal(roundedNow));const start=new Date(roundedNow);start.setDate(start.getDate()-7);const fromDraft=ref(toLocal(start));
const memberDraft=ref("");const group=ref<WithdrawalGroup>("day");const result=ref<WithdrawalReport|null>(null);const error=ref("");const exportError=ref("");const busy=ref(false);const exportBusy=ref(false);
const offset=ref(0);
let ticket=0;let exportTicket=0;let alive=true;
const scope=computed(()=>JSON.stringify({brand:props.brandId,id:props.account.id,super:props.account.super_admin,brands:[...(props.account.brand_ids??[])].sort(),permissions:[...(props.account.permissions??[])].sort(),platform:[...(props.account.platform_permissions??[])].sort(),byBrand:[...(props.account.permissions_by_brand?.[props.brandId]??[])].sort(),allowed:permissions.value}));
function clear(){result.value=null;error.value="";busy.value=false;ticket++;}
function queryRange(){const from=new Date(fromDraft.value),to=new Date(toDraft.value);if(!Number.isFinite(from.getTime())||!Number.isFinite(to.getTime())||to<=from||to.getTime()-from.getTime()>93*86400000)throw new Error(t("时间范围必须大于零且不超过 93 天。","Choose a valid range no longer than 93 days."));const member=memberDraft.value.trim();if(member&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(member))throw new Error(t("会员 UUID 格式无效。","Enter a valid member UUID."));return {from:from.toISOString(),to:to.toISOString(),group_by:group.value,...(member?{member_id:member}:{})};}
async function run(nextOffset=0,base?:WithdrawalReport["query"]){const local=scope.value;const id=++ticket;offset.value=nextOffset;result.value=null;error.value="";exportError.value="";if(!permissions.value.view){error.value=t("缺少提现报表查看权限","Missing report_withdrawal.view.brand or .platform grant.");return;}let query:WithdrawalReportQuery;try{query=base?{from:base.from,to:base.to,group_by:base.group_by,limit:base.limit,offset:nextOffset,...(base.member_id?{member_id:base.member_id}:{})}:{...queryRange(),limit:20,offset:nextOffset}}catch(e){error.value=e instanceof Error?e.message:t("筛选无效","Invalid filters.");return;}busy.value=true;try{const data=await api.report(props.brandId,query);if(alive&&ticket===id&&scope.value===local)result.value=data;}catch(e){if(alive&&ticket===id&&scope.value===local){result.value=null;error.value=e instanceof Error?e.message:t("读取失败","Unable to load report.");if(e instanceof AdminApiError&&e.status===401)emit("session-invalid");}}finally{if(ticket===id)busy.value=false;}}
async function exportAll(){if(!permissions.value.export||!result.value||!alive)return;const id=++exportTicket,local=scope.value,saved=result.value;exportBusy.value=true;exportError.value="";try{const file=await api.exportCsv(props.brandId,{from:saved.query.from,to:saved.query.to,group_by:saved.query.group_by,...(saved.query.member_id?{member_id:saved.query.member_id}:{})});if(!alive||id!==exportTicket||local!==scope.value||saved!==result.value)return;const url=URL.createObjectURL(new Blob([file.bytes],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=file.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}catch(e){if(alive&&id===exportTicket&&local===scope.value){exportError.value=e instanceof Error?e.message:"导出失败 / Export failed.";if(e instanceof AdminApiError&&e.status===401)emit("session-invalid");}}finally{if(id===exportTicket)exportBusy.value=false;}}
const metrics=(v:WithdrawalReport["summary"])=>[[t("申请数","Orders"),v.order_count],[t("申请积分","Requested points"),v.requested_points],[t("审核中","Reviewing"),v.reviewing_count],[t("审核中积分","Reviewing points"),v.reviewing_points],[t("提现中","Processing"),v.processing_count],[t("提现中积分","Processing points"),v.processing_points],[t("已提现","Paid"),v.paid_count],[t("已提现积分","Paid points"),v.paid_points],[t("已驳回","Rejected"),v.rejected_count],[t("已驳回积分","Rejected points"),v.rejected_points],[t("失败","Failed"),v.failed_count],[t("失败积分","Failed points"),v.failed_points],[t("已取消","Cancelled"),v.cancelled_count],[t("已取消积分","Cancelled points"),v.cancelled_points]] as const;
function exact(v:string){try{return BigInt(v).toLocaleString(locale.value==="en"?"en-US":"zh-CN")}catch{return v}}
function hasNext(value:WithdrawalReport){try{return BigInt(value.query.offset)<1_000_000n&&BigInt(value.query.offset)+BigInt(value.items.length)<BigInt(value.total_groups)}catch{return false}}
function groupLabel(key:string){if(result.value?.query.group_by!=="state")return key;const labels:Record<string,[string,string]>={reviewing:["审核中","Reviewing"],processing:["提现中","Processing"],paid:["已提现","Paid"],rejected:["已驳回","Rejected"],failed:["失败","Failed"],cancelled:["已取消","Cancelled"]};const pair=labels[key];return pair?t(pair[0],pair[1]):key}
watch(scope,()=>{clear();offset.value=0;exportTicket++;exportBusy.value=false;exportError.value="";if(!permissions.value.view)error.value=t("缺少提现报表查看权限","Missing report_withdrawal.view.brand or .platform grant.")},{flush:"sync"});
onBeforeUnmount(()=>{alive=false;ticket++;exportTicket++;});
</script>

<template>
  <section class="withdrawal-report" aria-labelledby="withdrawal-report-title">
    <header><div><h3 id="withdrawal-report-title">{{t("提现报表","Withdrawal report")}}</h3><p>{{t("只读申请队列投影","Read-only request projection")}}</p></div><button type="button" :disabled="busy" @click="() => run()">{{t("查询","Query")}}</button></header>
    <p class="definition">{{t("按申请创建时间 created_at 过滤 [from, to)，按品牌 IANA 时区分日。状态与积分是当前订单状态快照；不是不可变结账数据，也不是出款发生时间或外部转账记录。仅为内部积分记录，不代表真实支付。","Filters by application created_at in [from, to), groups days in the brand IANA timezone, and shows current order-state snapshots—not immutable closeout, payout time, or external transfers. These are internal points records and do not represent real payments.")}}</p>
    <div class="filters"><label>{{t("开始时间","From")}}<input v-model="fromDraft" type="datetime-local" step="1"></label><label>{{t("结束时间","To")}}<input v-model="toDraft" type="datetime-local" step="1"></label><label>{{t("会员 UUID","Member UUID")}}<input v-model.trim="memberDraft" autocomplete="off"></label><label>{{t("分组","Group by")}}<select v-model="group" :aria-label="t('分组','Group by')"><option value="day">{{t("按天","Day")}}</option><option value="member">{{t("按会员","Member")}}</option><option value="state">{{t("按状态","State")}}</option></select></label></div>
    <p v-if="props.account.super_admin" class="definition">{{t("超级管理员仍需显式获得查看和导出权限。","Super admins still need explicit view and export grants.")}}</p>
    <p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="exportError" class="error" role="alert">{{ exportError }}</p>
    <template v-if="result">
      <div class="context"><span>{{t("品牌","Brand")}} {{result.brand_id}}</span><span>{{t("快照","Snapshot")}} {{new Date(result.snapshot_at).toLocaleString()}}</span><span>{{t("品牌时区","Brand timezone")}} {{result.timezone}}</span><span>{{t("区间","Range")}} [{{result.query.from}}, {{result.query.to}})</span><span>{{t("会员","Member")}} {{result.query.member_id??t("全部","All")}}</span><span>{{t("总分组","Groups")}} {{exact(result.total_groups)}}</span></div>
      <div class="actions"><button type="button" :disabled="!permissions.export||exportBusy" @click="exportAll">{{exportBusy?t("导出中…","Exporting…"):t("导出完整 CSV","Export full CSV")}}</button><span v-if="!permissions.export">{{t("需要独立导出授权","Separate export grant required")}}</span></div>
      <div class="metrics"><div v-for="m in metrics(result.summary)" :key="m[0]"><span>{{m[0]}}</span><strong>{{exact(m[1])}}</strong></div></div>
      <div v-if="result.items.length" class="table-wrap"><table><thead><tr><th>{{t("分组键","Key")}}</th><th>{{t("标签","Label")}}</th><th v-for="m in metrics(result.items[0]!.totals)" :key="m[0]">{{m[0]}}</th></tr></thead><tbody><tr v-for="item in result.items" :key="item.key"><td>{{groupLabel(item.key)}}</td><td>{{groupLabel(item.label)}}</td><td v-for="m in metrics(item.totals)" :key="m[0]">{{exact(m[1])}}</td></tr></tbody></table></div>
      <p v-else class="definition">{{t("本页没有分组；上方汇总仍表示完整筛选范围的总计，可能非零。","No groups on this page. The summary above still covers the full filter range and may be nonzero.")}}</p>
      <nav class="pages"><span>{{result.query.offset+1}}–{{result.query.offset+result.items.length}} / {{exact(result.total_groups)}}</span><button type="button" :disabled="busy||result.query.offset===0" @click="run(Math.max(0,result.query.offset-20),result.query)">{{t("上一页","Previous")}}</button><button type="button" :disabled="busy||!hasNext(result)" @click="run(result.query.offset+20,result.query)">{{t("下一页","Next")}}</button></nav>
    </template>
    <p v-else-if="busy" class="definition" aria-live="polite">{{t("读取中…","Loading…")}}</p>
  </section>
</template>

<style scoped>
.withdrawal-report{display:grid;gap:12px;min-width:0;border:1px solid #d9e0ea;border-radius:12px;padding:16px;background:#fff;color:#172033}.withdrawal-report header,.actions,.pages{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.withdrawal-report h3,.withdrawal-report header p{margin:0}.withdrawal-report header p,.definition,.context,.actions span{color:#667085;font-size:.86rem;line-height:1.55}.filters{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.filters label{display:grid;gap:5px;min-width:0;font-size:.86rem}.filters input,.filters select{box-sizing:border-box;width:100%;min-width:0;padding:9px;border:1px solid #cbd3df;border-radius:8px;font:inherit}.withdrawal-report button{min-height:40px;padding:8px 12px;border:1px solid #c5ceda;border-radius:8px;background:#fff;color:inherit;font:inherit}.withdrawal-report button:disabled{opacity:.5}.context{display:flex;flex-wrap:wrap;gap:4px 14px;overflow-wrap:anywhere}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:8px}.metrics div{display:grid;gap:5px;min-width:0;border:1px solid #e5eaf0;border-radius:8px;padding:10px}.metrics span{color:#667085;font-size:.8rem}.metrics strong{overflow-wrap:anywhere;font-variant-numeric:tabular-nums}.table-wrap{overflow:auto;border:1px solid #e2e7ef;border-radius:8px}table{border-collapse:collapse;min-width:980px;width:100%;font-variant-numeric:tabular-nums}th,td{padding:8px;border-bottom:1px solid #edf0f4;text-align:left;white-space:nowrap}th{position:sticky;top:0;background:#f7f9fc}.error{margin:0;padding:10px;border-radius:8px;background:#fff0ee;color:#a32e1a}@media(max-width:700px){.withdrawal-report{padding:12px}.filters{grid-template-columns:minmax(0,1fr)}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.table-wrap{max-height:60vh}.actions button{width:100%}}
</style>
