export const commonSchemas = {
  UUID: { type: "string", format: "uuid" },
  DateTime: { type: "string", format: "date-time" },
  Int64String: { type: "string", pattern: "^(0|-?[1-9][0-9]*)$", description: "Exact signed int64 decimal string, within -9223372036854775808..9223372036854775807. Server enforces the numeric bound; the schema checks canonical decimal syntax. Never convert financial values to JavaScript Number." },
  NonnegativeInt64String: { type: "string", pattern: "^(0|[1-9][0-9]*)$", description: "Exact decimal integer string in 0..9223372036854775807." },
  PositiveInt64String: { type: "string", pattern: "^[1-9][0-9]*$", description: "Exact decimal integer string in 1..9223372036854775807." },
  PositiveInteger: { type: "integer", minimum: 1, format: "int64", description: "Positive JSON integer; server enforces int64 bounds. Numeric versions are not financial amounts." },
  Reason: { type: "string", minLength: 1, maxLength: 500, description: "Nonblank valid UTF-8; limit is 500 bytes, not characters. Leading/trailing spaces are normalized by the applicable handler." },
  EmptyObject: { type: "object", additionalProperties: false },
  ArbitraryJSON: { description: "Opaque JSON explicitly accepted/emitted by the relevant domain. This does not imply arbitrary financial writes or configurable rules outside the handler's validation." },
  ErrorResponse: { type: "object", required: ["success", "error", "request_id"], additionalProperties: false,
    properties: { success: { const: false }, error: { type: "object", required: ["code", "message"], additionalProperties: false, properties: { code: { type: "string" }, message: { type: "string" } } }, request_id: { type: "string" } } },
};
const ref = name => ({ $ref: `#/components/schemas/${name}` });
const responseHeaders = {
  "X-Request-ID": { description: "Correlation identifier, echoed or generated by middleware.", schema: { type: "string" } },
  "Cache-Control": { description: "Dynamic API responses are not cacheable.", schema: { type: "string", const: "no-store" } },
};
function success(data) { return { type: "object", required: ["success", "data", "request_id"], additionalProperties: false,
  properties: { success: { const: true }, data, request_id: { type: "string" } } }; }
export function operationKey(method, path) { return `${method.toUpperCase()} ${path}`; }
export function documentedRoutes(doc) { return Object.entries(doc.paths).flatMap(([path, item]) => Object.keys(item).filter(k=>["get","post","put","patch","delete"].includes(k)).map(method=>operationKey(method,path))).sort(); }
export function composeDocument(fragments, routes) {
  const schemas={...commonSchemas}, ops=[];
  for(const fragment of fragments){for(const [key,value] of Object.entries(fragment.schemas??{})){if(Object.hasOwn(schemas,key))throw new Error(`Duplicate schema ${key}`);schemas[key]=value}ops.push(...fragment.operations)}
const doc={openapi:"3.1.1",info:{title:"Lottery Platform Implemented API",version:"0.1.0",description:"Current implemented API only. Target 500 betting requests/s is not verified production capacity. Withdrawal order workflows and configured turnover eligibility are implemented. Commission cycles, audited point payouts, whole-cycle manual approval for mixed snapshot modes, adjustments and posting reports are implemented; payout policies default off. Manual reward order APIs support audited grants, full original gift-source reversals and explicit shortage continuation. Draw-correction commission compensation and reward UI, notifications and reporting remain incomplete. Real payment is not connected, and external draw API/DOM adapters remain stubbed. Browser user sessions use brand-named HttpOnly cookies; bearer tokens are supported for nonbrowser clients. Preserve Host through a trusted reverse proxy; a brand path cannot override a dedicated brand domain. See repository docs/04-api-contract.md and implementation-progress.md for business invariants and accepted scope."},servers:[{url:"/",description:"Same-origin configured application ingress; host determines user brand."}],tags:[],paths:{},components:{schemas,securitySchemes:{userBearer:{type:"http",scheme:"bearer",description:"Global-user session token bound to a brand member; never an admin token. Browser equivalents are lottery_user_<brandUUID_without_hyphens> HttpOnly cookies. Dynamic cookie names are described here rather than inventing a fixed Cookie header."},adminBearer:{type:"http",scheme:"bearer",description:"Administrative session; requires current account/role/brand grants."},adminCookie:{type:"apiKey",in:"cookie",name:"lottery_admin",description:"Same-origin HttpOnly administrator cookie; does not authenticate user endpoints."}}}};
  const ids=new Set(), tags=new Set();
  function append(source,path,alias){
    const method=source.method.toLowerCase();if(!["get","post","put","patch","delete"].includes(method))throw new Error(`Invalid method ${source.method}`);
    const opId=source.operationId+(alias?"ByBrand":"");if(!opId||ids.has(opId))throw new Error(`Duplicate/missing operationId ${opId}`);ids.add(opId);
    const hasData=Object.hasOwn(source,"data"),hasSuccessContent=Object.hasOwn(source,"successContent");
    if(!source.summary||!source.tag||!source.auth||hasData===hasSuccessContent||hasData&&source.data===undefined)throw new Error(`Incomplete or conflicting success declaration ${source.operationId}`);
    if(hasSuccessContent&&(!source.successContent||typeof source.successContent!=="object"||Array.isArray(source.successContent)||Object.keys(source.successContent).length===0||Object.entries(source.successContent).some(([mediaType,media])=>!mediaType||!media||typeof media!=="object"||Array.isArray(media)||!media.schema||typeof media.schema!=="object"||Array.isArray(media.schema))))throw new Error(`Invalid successContent ${source.operationId}`);
    tags.add(source.tag);const params=[...(source.parameters??[])];
    for(const match of path.matchAll(/\{([^}]+)\}/g)){const name=match[1];if(!params.some(p=>p.in==="path"&&p.name===name))params.push({name,in:"path",required:true,schema:name==="brandCode"?{type:"string"}:ref("UUID")})}
    params.push({name:"X-Request-ID",in:"header",required:false,schema:{type:"string",pattern:"^[a-zA-Z0-9_.:-]{1,80}$"},description:"Accepted correlation syntax; invalid or missing identifiers are replaced by the server."});
    if(source.brandHeader)params.push({name:"X-Brand-ID",in:"header",required:true,schema:ref("UUID"),description:"Selected brand; server revalidates current administrative scope and permission."});
    if(source.idempotency)params.push({name:"Idempotency-Key",in:"header",required:true,schema:{type:"string",pattern:"^[A-Za-z0-9_:.-]{8,128}$"},description:"Unique operation intent. Unknown result retries preserve this key and exactly the same body. Same key/different body returns409; successful cached receipts describe the original result, not live state."});
    if(method!=="get")params.push({name:"Origin",in:"header",required:false,schema:{type:"string"},description:"Required when any Cookie is sent: must match the original request Host and accepted scheme. Bearer-only nonbrowser requests may omit it. Client must not forge forwarded Host/IP."});
    if(!["public","user","admin","session"].includes(source.auth))throw new Error(`Invalid auth ${source.auth}`);
    const paramKeys=new Set();for(const p of params){const key=`${p.in}:${p.name.toLowerCase()}`;if(paramKeys.has(key))throw new Error(`Duplicate parameter ${opId} ${key}`);paramKeys.add(key)}
    const security=source.auth==="public"?[]:source.auth==="admin"?[{adminBearer:[]},{[path.startsWith("/api/v1/platform/")?"platformAdminCookie":"adminCookie"]:[]}]:[{userBearer:[]}];
    const status=String(source.successStatus??200),responses={};
    responses[status]={description:source.successDescription??"Matching successful receipt/data. Writes are acknowledged before independent reads of current state.",headers:{...responseHeaders,...(source.successHeaders??{})},content:hasSuccessContent?source.successContent:{"application/json":{schema:success(source.data)}}};
    const errorDescriptions={400:"Invalid input",401:"Session unavailable",403:"Permission/scope/origin rejected",404:"Resource or route unavailable",409:"Version/state/idempotency conflict",413:"Requested export exceeds its size or group limit",415:"JSON content type required",422:"Size limit exceeded; returns a JSON error with the operation-specific error code and no partial data",429:"Persistent authentication or admission rate limit",500:"Internal error",503:"Service or storage unavailable"};
    for(const code of [...new Set([400,401,403,404,409,415,429,500,503,...(source.additionalErrorStatuses??[])])]){
      if(!errorDescriptions[code])throw new Error(`Invalid additional error status ${code} for ${opId}`);
      responses[code]={description:errorDescriptions[code],headers:responseHeaders,content:{"application/json":{schema:ref("ErrorResponse")}}};
    }
    const op={operationId:opId,summary:source.summary,tags:[source.tag],description:source.description??"",security,parameters:params,responses,"x-implemented":true,"x-permissions":source.permissions??[],"x-idempotent-operation":Boolean(source.idempotency)};
    if(source.requestBody)op.requestBody={required:true,description:"Exactly one JSON object, at most16KiB; unknown fields rejected where documented. JSON Schema cannot represent duplicate-member rejection; see handler contract.",content:{"application/json":{schema:source.requestBody}}};
    if(method!=="get"&&!source.requestBody)throw new Error(`Missing request schema ${opId}`);
    if(doc.paths[path]?.[method])throw new Error(`Duplicate operation ${operationKey(method,path)}`);(doc.paths[path]??={})[method]=op;
  }
  doc.components.securitySchemes.platformAdminCookie={type:"apiKey",in:"cookie",name:"lottery_platform_admin",description:"Independent platform-only HttpOnly cookie, restricted to /api/v1/platform; only super administrator accounts are accepted."};
  for(const source of ops){
    append(source,source.path,false);
    if(source.path.startsWith("/api/v1/admin/")){
      const path=source.path.replace("/api/v1/admin/","/api/v1/platform/");
      if(routes.some(route=>route.method===source.method&&route.path===path)){
        append({...source,operationId:source.operationId+"Platform",summary:"Platform: "+source.summary,description:"Independent platform entry: only super administrator accounts are accepted; brand staff accounts are rejected. Only platform-scoped grants are considered. Platform business reads remain permission checked. Account and role management are registered explicitly; brand member edits, approvals and financial mutations remain unregistered. "+(source.path==="/api/v1/admin/brand-operation"&&source.method==="PATCH"?"Brand pause/resume is also registered explicitly, requires brand_operation.write.platform, and retains version checks, idempotent receipts and audited status history. Paused brands may still log in and withdraw; new bets are rejected and existing orders continue. ":"")+(source.description??"")},path,false);
      }
      doc.paths[source.path][source.method.toLowerCase()].description="Brand staff entry (administrator, operations, finance or customer support according to configured roles); platform accounts are rejected and platform-scoped grants cannot widen brand access. "+(source.description??"");
    }else if(source.path.startsWith("/api/v1/")&&!source.path.startsWith("/api/v1/platform/")){
      append(source,source.path.replace("/api/v1/","/api/v1/b/{brandCode}/"),true);
    }
  }
  doc.tags=[...tags].sort().map(name=>({name,description:`Implemented ${name} interfaces.`}));
  assertCoverage(doc,routes);assertReferences(doc);return doc;
}
export function assertCoverage(doc,routes){const actual=new Set(routes.map(r=>operationKey(r.method,r.path))), documented=new Set(documentedRoutes(doc));const missing=[...actual].filter(k=>!documented.has(k)),invented=[...documented].filter(k=>!actual.has(k));if(missing.length||invented.length)throw new Error(`Route coverage mismatch\nMissing: ${missing.join(", ")}\nUnregistered: ${invented.join(", ")}`)}
export function assertReferences(doc){function walk(value){if(!value||typeof value!=="object")return;if(typeof value.$ref==="string"){if(!value.$ref.startsWith("#/"))throw new Error(`External reference not allowed: ${value.$ref}`);let target=doc;for(const key of value.$ref.slice(2).split("/").map(k=>k.replaceAll("~1","/").replaceAll("~0","~"))){target=target?.[key];if(target===undefined)throw new Error(`Unresolved reference ${value.$ref}`)}}for(const child of Object.values(value))walk(child)}walk(doc)}
